export const SECTION_VIEW_CONFIG = {
  paraViewSections: [
    'Data Management Persistence',
    'Purpose',
    'Audience',
    'Scope',
    'Relationships',
  ],
  listViewSections: [
    'Error Handling',
    'User Roles',
    'Regular User',
    'User Interface Design',
    'Product Perspective',
    'User Classes Characteristics',
    'Feature Descriptions',
    'Product Functions',
    'Performance Metrics',
    'Deployment',
    'Technology Stack',
    'Security',
    'Reporting Requirements',
    'Usability',
    'Reliability',
    'Availability',
    'Scalability',
    'Maintainability',
    'Portability',
    'Integration Points',
    'References',
    'UserClasses Characteristics',
    'System Architecture',
    'Functional Assumptions',
    'Functional Known Issues',
    'Technical Known Issues',
    'Technical Assumptions',
    'Hardware Interfaces',
    'Software Interfaces',
  ],
  userRoleSection: ['User Roles'],
  userPersonaSection: ['User Personas'],
};
