export const SECTION_VIEW_CONFIG = {
    paraViewSections: [
        'System Architecture',
        'Hardware Interfaces',
        'Software Interfaces',
        'Functional Assumptions',
        'Technical Assumptions',
        'Functional Known Issues',
        'Technical Known Issues',
        'Purpose',
        'Audience',
        'Scope',
        'References',
        'UserClasses Characteristics',
        'Data Model',
        'Relationships',
    ],
    listViewSections: [
        'Product Perspective',
        'User Classes Characteristics',
        'Feature Descriptions',
        'Product Functions',
        'Performance Metrics',
        'Deployment',
        'Technology Stack',
        'Security',
        'Reporting Requirements',
        'Usability',
        'Reliability',
        'Availability',
        'Scalability',
        'Maintainability',
        'Portability',
        'Integration Points',

    ]
}