export const SECTION_VIEW_CONFIG = {
  paraViewSections: [
    'Data Management Persistence',
    'Purpose',
    'Audience',
    'Scope',
    'Relationships',

    'Background',
    'Objectives',
    'Target Audience',
    'Key Features',
    'Context',
    'Objectives',
    'Relevance',
    'Justification',
    'Comprehensive Analytics App',
    'Ease of Use Emphasis',
    'Informative Visualizations',
    'Seamless Data Integration',
    'Product Goals',
    'Standout Features',
    'Benefits',
    'Market Research',
    'Defining Problems and Goals',
    'Researching Existing Solutions',
    'Feasibility Studies',
    'Conclusion',
    'Main Goals',
    'Key Requirements and Considerations',
    'Partnerships and Collaborations',
    'Application Features and Requirements',
    'Development and Improvement Strategies',
    'Maintenance and Bug Fixes',
    'Risk Management and Compliance'

  ],
  listViewSections: [
    'Error Handling',
    'User Roles',
    'Regular User',
    'User Interface Design',
    'Data Management Persistence',
    'Product Perspective',
    'User Classes Characteristics',
    'Feature Descriptions',
    'Product Functions',
    'Performance Metrics',
    'Deployment',
    'Technology Stack',
    'Security',
    'Reporting Requirements',
    'Usability',
    'Reliability',
    'Availability',
    'Scalability',
    'Maintainability',
    'Portability',
    'Integration Points',
    'References',
    'UserClasses Characteristics',
    'System Architecture',
    'Functional Assumptions',
    'Functional Known Issues',
    'Technical Known Issues',
    'Technical Assumptions',
    'Hardware Interfaces',
    'Software Interfaces',

    'Performance Optimization',
    'Data Management',
    'Tasks and Suggestions',
    'Product Overview',
    'Product Requirements',
    'Use Case Suggestions',
    'Potential Benefits',
    'Next Steps',
    'User Accounts',
    'Budget'

  ],
  userRoleSection: ['User Roles'],
  userPersonaSection: ['User Personas'],
};
