export const environment = {
    name: 'DEV',
    production: false,
    apiUrl: 'https://xnode-us-apim-dev.azure-api.net/navi-api/',
    // apiUrl: 'http://localhost:8000/',
    authApiUrl: 'https://xnode-us-apim-dev.azure-api.net/auth-api/',
    conversationApiUrl: 'https://xnode-us-apim-dev.azure-api.net/conversations-api/',
    commentsApiUrl: 'https://xnode-us-apim-dev.azure-api.net/spec-api/',
    notifyApiUrl: 'https://xnode-us-apim-dev.azure-api.net/notification-api/',
    userUtilsApi: 'https://xnode-us-apim-dev.azure-api.net/userutil-api/',
    commonApiUrl: 'https://xnode-us-apim-dev.azure-api.net/common-api/',
    xnodeAppUrl: 'http://localhost:4200/',
    naviAppUrl: 'https://dev-navi-web.azurewebsites.net/',
    designStudioAppUrl: 'http://localhost:4201/dashboard/',
    publishApiUrl: 'https://dev-frontend-builder.azurewebsites.net/ui/angular/',
    uigenApiUrl: 'https://xnode-us-apim-dev.azure-api.net/ui-gen/ui/angular/',
    workFlowApiUrl: 'https://dev-xnode-xflows.azurewebsites.net/',
    webSocketUrl: 'https://notify-now.azurewebsites.net',
    webSocketNotifier: 'dev-xnode-notifier',
    branchName: 'dev',
    projectName: 'xnode-dev',
    homeUrl: 'https://dev.xnode.ai/',
    XNODE_IDLE_TIMEOUT_PERIOD_SECONDS: '30 * 60',
    XNODE_TIMEOUT_PERIOD_SECONDS:30
}
