export const environment = {
  name: 'DEV',
  production: false,
  apiUrl: 'https://dev-navi-api.azurewebsites.net/',
  authApiUrl: 'https://dev-xnode-auth-api.azurewebsites.net/',
  commentsApiUrl: 'https://dev-spec-api.azurewebsites.net/',
  notifyApiUrl: 'https://dev-notify-api.azurewebsites.net/',
  userUtilsApi: 'https://dev-user-util-api.azurewebsites.net/',
  commonApiUrl: 'https://dev-cmn-api.azurewebsites.net/',
  xnodeAppUrl: 'http://localhost:4200/',
  naviAppUrl: 'https://dev-navi-web.azurewebsites.net/',
  designStudioAppUrl: 'https://dev-ui-gen.azurewebsites.net/dashboard/',
  publishApiUrl: 'https://dev-frontend-builder.azurewebsites.net/ui/angular/',
  uigenApiUrl: 'https://dev-frontend-builder.azurewebsites.net/',
  workFlowApiUrl: 'https://dev-xnode-xflows.azurewebsites.net/',
  webSocketUrl: 'https://notify-now.azurewebsites.net',
  webSocketNotifier: 'dev-xnode-notifier',
  branchName: 'dev',
  projectName: 'xnode',
  homeUrl: 'https://dev.xnode.ai/',
};
