export const environment = {
    name: 'BETA',
    production: false,
    apiUrl: 'https://xnode-us-apim.azure-api.net/',
    apimSubscriptionKey: '64182f1412f74e0fb4402f476e10d567',
    endpoints: {
        navi: 'navi-api',
        auth: 'auth-api',
        conversation: 'conversation-api',
        spec: 'spec-api',
        userUtil: 'userutil-api',
        common: 'common-api',
        naviData: 'navi-data',
        publish: 'ui-gen/ui/angular',
        notification: 'notification-api'
    },
    authApiUrl: 'https://beta-xnode-auth-api.azurewebsites.net/',
    conversationApiUrl: 'https://beta-conversation-api.azurewebsites.net/',
    commentsApiUrl: 'https://beta-spec-api.azurewebsites.net/',
    notifyApiUrl: 'https://beta-notify-api.azurewebsites.net/',
    userUtilsApi: 'https://beta-user-util-api.azurewebsites.net/',
    commonApiUrl: 'https://beta-cmn-api.azurewebsites.net/',
    xnodeAppUrl: 'https://app-us.xnode.ai/',
    naviAppUrl: 'https://beta-navi-web.azurewebsites.net/',
    designStudioAppUrl: 'https://beta-ui-gen.azurewebsites.net/dashboard/',
    publishApiUrl: 'https://beta-frontend-builder.azurewebsites.net/ui/angular/', //for now we have only dev url
    uigenApiUrl: 'https://beta-frontend-builder.azurewebsites.net/',
    workFlowApiUrl: 'https://beta-xnode-xflows.azurewebsites.net/',
    webSocketUrl: 'https://notify-now-us.azurewebsites.net',
    webSocketNotifier: 'beta-xnode-notifier',
    branchName: 'beta',
    projectName: 'xnode-beta',
    homeUrl: 'https://xnode.ai/',
    XNODE_IDLE_TIMEOUT_PERIOD_SECONDS: '30 * 60',
    XNODE_TIMEOUT_PERIOD_SECONDS: 30
}
