export const environment = {
    name: 'DEMO',
    production: false,
    apiUrl: 'https://demo-navi-api.azurewebsites.net/',
    authApiUrl: 'https://demo-xnode-auth-api.azurewebsites.net/',
    conversationApiUrl: 'https://demo-conversation-api.azurewebsites.net/',
    commentsApiUrl: 'https://demo-spec-api.azurewebsites.net/',
    notifyApiUrl: 'https://demo-notify-api.azurewebsites.net/',
    userUtilsApi: 'https://demo-user-util-api.azurewebsites.net/',
    commonApiUrl: 'https://demo-cmn-api.azurewebsites.net/',
    xnodeAppUrl: 'https://demo-xnode.azurewebsites.net/',
    naviAppUrl: 'https://demo-navi-web.azurewebsites.net/',
    designStudioAppUrl: 'https://demo-ui-gen.azurewebsites.net/dashboard/',
    workFlowApiUrl: 'https://demo-xnode-xflows.azurewebsites.net/',
    webSocketUrl: 'https://notify-now.azurewebsites.net',
    webSocketNotifier: 'demo-xnode-notifier',
    branchName: 'demo',
    projectName: 'xnode-demo',
    homeUrl: 'https://xnode.ai/',
    XNODE_IDLE_TIMEOUT_PERIOD_SECONDS: '30 * 60',
    XNODE_TIMEOUT_PERIOD_SECONDS: 30
}
