export const sampleData: any = {
  "app_type": "web",
  "use_laravel_auth": false,
  "models": [
    {
      "schemas": [
        {
          "id": 2,
          "name": "column2",
          "display_name": "column2",
          "comment": "column2",
          "type": "text",
          "input_type": "number",
          "custom_options": "",
          "varidate": "column2",
          "faker_type": "",
          "nullable": true,
          "unique": false,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "",
          "parent_id": 1
        },
        {
          "id": 1,
          "name": "column1",
          "display_name": "column1",
          "comment": "column1",
          "type": "string",
          "input_type": "text",
          "custom_options": "",
          "varidate": "",
          "faker_type": null,
          "nullable": false,
          "unique": true,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "",
          "parent_id": 1
        }
      ],
      "id": 1,
      "name": "test",
      "display_name": "test",
      "comment": "sdsd",
      "use_soft_delete": false,
      "is_pivot": false,
      "schema_id_for_relation": 2,
      "module": "modul1",
      "pos_x": 247,
      "pos_y": 303,
      "_next_schema_id": 3
    },
    {
      "schemas": [
        {
          "id": 1,
          "name": "tabcol1",
          "display_name": "tabcol1",
          "comment": "tabcol1",
          "type": "string",
          "input_type": "email",
          "custom_options": "",
          "varidate": "tabcol1",
          "faker_type": "",
          "nullable": false,
          "unique": true,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "",
          "parent_id": 2
        },
        {
          "id": 2,
          "name": "test_id",
          "display_name": "test - NAME",
          "comment": "",
          "type": "integer",
          "input_type": "select",
          "custom_options": "",
          "varidate": "",
          "faker_type": "numberBetween(1,30)",
          "nullable": true,
          "unique": false,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "test",
          "parent_id": 2
        }
      ],
      "id": 2,
      "name": "testtab2",
      "display_name": "testtab2",
      "comment": "testtab2",
      "use_soft_delete": false,
      "is_pivot": false,
      "schema_id_for_relation": 1,
      "module": "modul2",
      "pos_x": 662,
      "pos_y": 480,
      "_next_schema_id": 3
    },
    {
      "schemas": [
        {
          "id": 1,
          "name": "test_id",
          "display_name": "test - NAME",
          "comment": "",
          "type": "integer",
          "input_type": "select",
          "custom_options": "",
          "varidate": "",
          "faker_type": "numberBetween(1,30)",
          "nullable": true,
          "unique": false,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "test",
          "parent_id": 4
        },
        {
          "id": 2,
          "name": "tablecol3",
          "display_name": "tablecol3",
          "comment": "tablecol3",
          "type": "string",
          "input_type": "text",
          "custom_options": "",
          "varidate": "column2",
          "faker_type": "",
          "nullable": false,
          "unique": false,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "",
          "parent_id": 4
        }
      ],
      "id": 4,
      "name": "table3",
      "display_name": "Table33",
      "comment": "test",
      "use_soft_delete": true,
      "is_pivot": false,
      "schema_id_for_relation": 2,
      "module": "tee",
      "pos_x": 652,
      "pos_y": 178,
      "_next_schema_id": 3
    },
    {
      "schemas": [
        {
          "id": 1,
          "name": "TableNoRelationCol1",
          "display_name": "TableNoRelationCol1",
          "comment": "TableNoRelationCol1",
          "type": "string",
          "input_type": "text",
          "custom_options": "",
          "varidate": "",
          "faker_type": "",
          "nullable": false,
          "unique": true,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "",
          "parent_id": 5
        },
        {
          "id": 2,
          "name": "TableNoRelationCol2",
          "display_name": "TableNoRelationCol2",
          "comment": "TableNoRelationCol2",
          "type": "string",
          "input_type": "text",
          "custom_options": "",
          "varidate": "",
          "faker_type": "",
          "nullable": false,
          "unique": false,
          "show_in_list": true,
          "show_in_detail": true,
          "belongsto": "",
          "parent_id": 5
        }
      ],
      "id": 5,
      "name": "TableNoRelation",
      "display_name": "TableNoRelation",
      "comment": "TableNoRelation",
      "use_soft_delete": false,
      "is_pivot": false,
      "schema_id_for_relation": 1,
      "module": "TableNoRelation",
      "pos_x": 949,
      "pos_y": 145,
      "_next_schema_id": 3
    }
  ],
  "tool": "ER-DIAGRAM-TOOL",
  "_next_model_id": 6
}
