
trigger:
- automated-dev

stages:
  - stage: build
    displayName: Build Application
    pool:  
      vmImage: 'ubuntu-latest'  
    jobs:
    - job: Build
      displayName: Build & Publish Artifacts
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'code-gen/pom.xml'
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false


      - task: PublishPipelineArtifact@1
        displayName: "Publish Artifacts"
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/code-gen'
          artifact: 'backendApp'
          publishLocation: 'pipeline'


  - stage: deploy 
    dependsOn: build
    displayName: "Deploy to Azure"
    jobs:
      - job: Deploy
        displayName: "Push Artifacts to WebApp"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: "Download Pipeline Artifacts"
            inputs:
              buildType: 'current'
              artifactName: 'backendApp'
              targetPath: '$(Build.ArtifactStagingDirectory)'
              
          - task: AzureRmWebAppDeployment@4
            displayName: "Deploy Artifacts to WebApp"
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'xnode-spn'
              appType: 'webAppLinux'
              WebAppName: 'dev-webreact'
              packageForLinux: '$(Build.ArtifactStagingDirectory)'
              RuntimeStack: 'JAVA|11-java11'