export enum MessageTypes {
    LinkToCR = "LINK_TO_CR",
    NAVI_CONTAINER_STATE = "NAVI_CONTAINER_STATE",
    PRODUCT_CONTEXT = "PRODUCT_CONTEXT",
    HAS_INSIGHTS = "HAS_INSIGHTS",
    CLOSE_NAVI = "CLOSE_NAVI",
    MAKE_TRUST_URL = "MAKE_TRUST_URL",
    OPEN_NAVI = "OPEN_NAVI"
}
